### ISSUE TITLE
[Question] is there a way to install this program on windows  machines?

### ISSUE THREAD

**Issue by megdeb** [OpenInternet/Documentation-Builder#6]
Only saw the installation instructions for ubuntu. :)

**Comment by joncamfield** [comment]
Currently the Windows build instructions are:

1) Install Ubuntu (or Debian!) as a virtual machine or on a server
2) Follow existing installation instructions

:)

**Comment by megdeb** [comment]
haha ... ohhhh how helpful ;)

thank you sir!

**Comment by joncamfield** [comment]
With the windows subsystem for Linux in Win10, using the Ubuntu 18.04 image and the python3 install instructions, this is possible. You will need to specify pip3 in the markdown installation instructions, and apt install these additional packages:

* libxrender1
* libfontconfig1
